### ISSUE TITLE
Unify tag names in formatted strings

### ISSUE THREAD

**Issue by clvLabs** [clvLabs/fortnitetracker-stats#2]
Try to use the _original_ api field names in formatted strings.

```json
        "trackerUrl": "https://fortnitetracker.com/profile/all/{user}/matches",
```

should be

```json
        "trackerUrl": "https://fortnitetracker.com/profile/all/{trn_username}/matches",
```

**Comment by clvLabs** [comment]
`ProfilePinger` already fixed, when `APIStatsGetter` has been reviewed the issue can be closed.

**Comment by gescudero** [comment]
APIStatsGetter was already well formatted.
