### ISSUE TITLE
Save profile data

### ISSUE THREAD

**Issue by gescudero** [clvLabs/fortnitetracker-stats#9]
It's a good idea to save the profile data in another file like matches history. Maybe later we can use that data to create progress graphics and so.

With this change we have to move the `apistatsgetter.fill_users_id()` to the `mainLoop()` to avoid two request for the same data

**Comment by gescudero** [comment]
I think will be nice to grab profile data from https://dash.fortnite-api.com/ instead of use the trackingnetwork version

**Comment by clvLabs** [comment]
Maybe both?

**Comment by clvLabs** [comment]
Check this: https://github.com/Fortnite-API/py-wrapper (official python wrapper)  👍🏼

**Comment by gescudero** [comment]
Now we grab profile data from both sources and save them, but only the last version, always overwriting the version we have.

**Comment by gescudero** [comment]
Finally I solved it making a new Profile class and saving in it the most valuable information. I'm using tracking network profile info because is more accurate than the fortnite-api info

**Comment by gescudero** [comment]
close
